### ISSUE TITLE
Seminar Slides: April 

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#101]
Need to get Seminar slides from Tania's talk.

Ideally these should be hosted in a separate repo to avoid polluting this repo with large binary files. Either:

+ Link to Tania's hosted copy
+ New org repo's `gh-pages` branch. I.e. new repo `seminar-slides` which would then resolve to `rse-sheffield.github.io/seminar-slides`. This would need to avoid mangling with any pages on the primary site.

**Comment by willfurnass** [comment]
@mozhgan-kch Did you get slides from the speaker?
