### ISSUE TITLE
Github branch protection for master

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#116]
We should prevent direct push's to the master branch, to avoid accidental pushes to the upstream master, which skips CI / review.

Only team members with admin access to the repo can do this @willfurnass ?

https://help.github.com/en/articles/enabling-branch-restrictions

**Comment by willfurnass** [comment]
Good idea.  I've enabled 'require status checks to pass before merging' for `master`.
