### ISSUE TITLE
Markdown tables look awful

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#118]
E.g. https://rse.shef.ac.uk/blog/dcs-gpus-for-bessemer/ as of 0203e600706ce4851385d3eb91f1ec6f67c52fe6

**Comment by ptheywood** [comment]
The bootstrap theme provides good tables, but a couple of classes need adding (i.e. not applied to tables overall). 

adding `class="table table-hover table-striped"` to the `<table>` and `class="thead-dark" to the inner `<thead>` element produces: 

![image](https://user-images.githubusercontent.com/628937/61389974-c9cf6200-a8b1-11e9-909a-5104c0feae5b.png)


Not sure how we can modify the markdown rendering to do this, but it shouldn't be too bad to extract the relevant css rules and make them apply globally to *all* tables. It would be fairly easy to make it apply to tables within a more sepcific parent element.

**Comment by ptheywood** [comment]
Kramdown allows the following snipped to get the better formatting (but not the darker header) very easily, but needs applying to all tables in markdown.

```
| NVLink bandwidth            | 300 GB/s      | 160 GB/s      |
{:.table.table-bordered.table-striped.table-hovered}
```
![image](https://user-images.githubusercontent.com/628937/61390696-2b440080-a8b3-11e9-8466-71d97a6b7443.png)



Via: https://gist.github.com/tamouse/4204dddabb6b072b0242
