### ISSUE TITLE
Advertise RSS feed

### ISSUE THREAD

**Issue by Bisaloo** [RSE-Sheffield/RSE-Sheffield.github.io#122]
Hi,

I'd like to stay up-to-date with your blog content by subscribing to a RSS feed of your posts. 

I was initially going to open an issue asking you if you would consider adding one but I see you actually already have one: https://rse.shef.ac.uk/feed.xml

It would be great if you could advertise via `meta` tags, as documented in the [`jekyll-feed` `README`](https://github.com/jekyll/jekyll-feed#meta-tags) so that tools like https://addons.mozilla.org/en-US/firefox/addon/awesome-rss/ can automatically detect it.

**Comment by willfurnass** [comment]
@Bisaloo Thanks for the suggestion; that's been implemented now.
