### ISSUE TITLE
Add profile page for Bob Turner

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#128]
@bobturneruk Please could you add a profile page to https://rse.shef.ac.uk (the group's Jekyll site).  See
 - https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/master/README.md for info on on how to build/test new contributions.
 - https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/tree/master/_people for profiles of existing team members. 

Please could you 
1. fork this repo
2. create a new branch
3. commit a profile page to this branch
4. test that you can build the site locally
5. create a Pull Request for this branch against the `master` branch of the `RSE-Sheffield/RSE-Sheffield.github.io` repo
6. Tag someone else in the team as a Reviewer

Do ask if you have any questions.

**Comment by ptheywood** [comment]
resolved by #129
