### ISSUE TITLE
Dead widget on code clinic page

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#143]
https://rse.shef.ac.uk/support/code-clinic/

![image](https://user-images.githubusercontent.com/34244196/65582260-f7511f80-df74-11e9-965a-bf72cf5b1730.png)

**Comment by bobturneruk** [comment]
@ptheywood says it may be something to do with whether one is logged on and maybe best to remove the widget altogether

**Comment by bobturneruk** [comment]
Relevant bit is here _layouts/codeclinic.html

**Comment by willfurnass** [comment]
@bobturneruk We can make the calendar visible to all (not just logged-in TUOS GSuite users) and show either all event info or just show available/busy.  We certainly don't want the former if that results in researcher's details being broadcasted and showing just available vs busy isn't desirable either as at present _all_ events in that calendar are marked as busy, regardless of whether there's a booking for the  corresponding CC slot.  

+1 for removing the iframe for now.

**Comment by ptheywood** [comment]
Closed by #145
