### ISSUE TITLE
Remove coffee and cake?

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#159]
It's nearly a year since the last one of these, by the look of it:

https://rse.shef.ac.uk/community/coffee-and-cake

Should we remove this from the site?

**Comment by ptheywood** [comment]
We can always just place any future coffee and cake events into the generic list of events if they were to happen.

**Comment by ptheywood** [comment]
I've made a PR to do this, but if anyone objects to it it doesn't need merging / can always be reverted.
