### ISSUE TITLE
Blank space on RSE community page

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#160]
No matter how much I sign in I see this:

![image](https://user-images.githubusercontent.com/34244196/66495970-0cb86480-eab2-11e9-93f2-9fab9e454686.png)

on the RSE community page:

https://rse.shef.ac.uk/community/

**Comment by Robadob** [comment]
This is the same issue you had for the calendar widget.

Works on my computer at home without issue.

**Comment by bobturneruk** [comment]
So it should be removed as per the calendar?

**Comment by Robadob** [comment]
I'd leave that decision to @twinkarma, he made it.

https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blame/master/pages/community/index.md

**Comment by ptheywood** [comment]
It's an embeded iframe for the mailing list, but it is limited to University google accounts only. 

I'd support it being removed - Iframes are horrible to interact with anyway. 

It may be worth modifying the text for the link to the mailing list if/when the iframe is removed.

**Comment by twinkarma** [comment]
It's a legacy from the old website. Same with the calendar in that we'd either have to make the group public to view or replace it with a link to the group.

It does have a part where you can log in and switch account if you're using the wrong one unlike the calendar widget so it is more viable. I'll leave it for @willfurnass  to decide, I think he put it in the original website?

**Comment by willfurnass** [comment]
I think we should remove the iframe and replace with a hyperlinked image.

**Comment by bobturneruk** [comment]
Resolved in current version.
