### ISSUE TITLE
Data clinic?

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#172]
Could / should we offer a "Data Clinic" via the website?

The back end of this would be managed in the same way as code clinic and no extra slots allocated. However, the page on the site would offer help on data analysis workflows where introducing a small amount of code might improve performance and repeatability.

I was going to put this in as an internal project, but it probably wouldn't require much effort if we decided to go ahead.

**Comment by willfurnass** [comment]
Could we just tweak the blurb we have for the existing service to suggest that those wanting to automate/streamline data analysis workflows would be welcome?

**Comment by bobturneruk** [comment]
I think that would be a great thing to do. I'll draft something on a branch and see what people think.
