### ISSUE TITLE
Social Media Cards (Open Graph)

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#178]
Blog posts (and website pages in general?) don't currently produce a social media card when linked in tweets etc.

This might be nice for sharing blog posts. 

Open Graph looks like twitter and facebook support it (along with other specific `<meta>` tags. 

This should be done for blog posts at a minimum.

**Comment by davidwyld** [comment]
A potential solution: https://www.brianbunke.com/blog/2017/09/06/twitter-cards-on-jekyll/#tweak-to-fit-your-needs
Although twitter-specific.

**Comment by davidwyld** [comment]
Have had a crack at this on this branch https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/tree/social-cards using [`jekyll-seo-tag`](https://github.com/jekyll/jekyll-seo-tag) but could do with testing using the [twitter card validator](https://cards-dev.twitter.com/validator)
Anyone (@Robadob :question:) want to build an online mirror to test?

**Comment by Robadob** [comment]
Ill try and put it in my fork.

**Comment by Robadob** [comment]
https://rse-mirror.robadob.org/

I've only cherrypicked your one commit from that branch, but it *should* be live now.

**Comment by davidwyld** [comment]
Okay, have added another commit to that branch c6686ac7c077208cdd4292e8f2163ab5ee6a1607
which adds 
```
defaults:
...
  - scope:
      path: ""
    values:
      image: /assets/images/rse-logoonly-stroke.png
```
to `config.yml` to define the RSE logo as the default image.

Also added:
```
image:
  path: /assets/images/gpuhack19/gpuhackthon.jpg
```
to the YAML front matter of `_posts/2019-10-10-gpu-hackathon.md`
to see if that specifies the image for a card successfully.

Cheers, @Robadob

**Comment by Robadob** [comment]
Updated again
