### ISSUE TITLE
Jekyll build failed on merging pull request #213

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#215]
Merge of PR #213 has happened, I can get it to serve the `master` branch when I build locally. The new event in from the pull request is not visible at https://rse.shef.ac.uk/events/

**Comment by willfurnass** [comment]
Might need to wait a few mins.

**Comment by bobturneruk** [comment]
It threw this via email:

>The page build failed for the `master` branch with the following error:
>
>Page build failed. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.
>
>For information on troubleshooting Jekyll see:
>
>  https://help.github.com/articles/troubleshooting-jekyll-builds
>
>If you have any questions you can contact us by replying to this email.

**Comment by ptheywood** [comment]
Last time something like this happened it was due gh-pages updating to a new version of jekyll, but it appears the last change was on Jan 24 so should have trigerred previously (https://github.com/github/pages-gem/releases)

**Comment by bobturneruk** [comment]
Still not working. I think an admin (@willfurnass or @mondus) will have to see if they can get at a log file so we can get some specific info on what's gone wrong.

**Comment by bobturneruk** [comment]
From @willfurnass :

>The repo settings just show 'page build failed' and don't appear to offer a more detailed error message or build logs.  GitHub's troubleshooting tips aren't much use either.  I tried creating a PR to trigger another build but that failed due to what looks like service issues.  See https://www.githubstatus.com/  These service issues may be the underlying cause of all of this 'fun'.
githubstatus.comgithubstatus.com
GitHub Status
Welcome to GitHub's home for real-time and historical data on system performance.
