### ISSUE TITLE
Code Clinics: add info re screen sharing 

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#225]
Following on from #224 we should add info to our Code Clinic docs re screen sharing.  This should probably include a statement re information security.  I've sent the following to the infosec team for approval:
 
> To help others help you it may be useful for you to share your screen via Chrome Remote Desktop (setup instructions [here](https://support.google.com/chrome/answer/1649523?co=GENIE.Platform%3DDesktop&hl=en)).  We ask that if you do choose to share your screen with a helper that you consider in advance whether you will be exposing confidential data/code/information that helpers are not permitted to view. If you have any questions regarding the information security implications of sharing your screen please contact the TUOS Information Security team via helpdesk@sheffield.ac.uk

cc @bobturneruk

**Comment by willfurnass** [comment]
Going to append:

> Note that Google Remote Desktop is not covered with our Google for Educators licence so any confidential information shared over this medium is only covered by Google's standard privacy policy.

**Comment by bobturneruk** [comment]
I believe this has been resolved by #228. @willfurnass are you happy to close?

**Comment by willfurnass** [comment]
Yep!
