### ISSUE TITLE
Guide to getting started with R and GIS 

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#23]
Discussed here

Migrated from RSE-Sheffield/old_team_site_nikola#42

**Comment by willfurnass** [comment]
@annakrystalli Think this is still of interest?  Someone from ITS may be interested in writing this if all in the RSE team are busy.  

NB we do have a bit of info on R + GIS here but it's largely HPC-specific reference info: https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/R.html

**Comment by ns-rse** [comment]
There is a Bookdown site written by Andrew MacLachlan for the course he teaches at UCL that we could point people to on this very topic [CASA0005 Geographic Information Systems and Science](https://andrewmaclachlan.github.io/CASA0005repo/)

He presented on it at the [Teaching Reproducible Research and Open Science Conference](https://www.sheffield.ac.uk/smi/events/teaching-reproducible-research-and-open-science-conference) last year. Very impressive as all the course is organised through GitHub Education with automated assessment of assignments (e.g. they have to pass the GitHub actions and produce reports).
