### ISSUE TITLE
Fix broken internal and external links

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#237]
HTTP 4xx errors identified using [htmlproofer](https://github.com/gjtorikian/html-proofer) (NB there may be more; htmlproofer crashed when crawling the site):

- _site/assets/plugins/jquery-scrollTo/index.html
  *  External link http://badge.fury.io/gh/flesler%2Fjquery.scrollTo failed: 429 No error
--
- _site/blog/2019-10-10-gpu-hackathon/index.html
  *  External link https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/#training-system-(ascent) failed: 404 No error
--
- _site/blog/2019-12-16-gpu-hackathon/index.html
  *  External link https://github.com/geraldgallagher/culbibbs failed: 429 No error
--
- _site/blog/codefirstgirls-meets-hacktoberfest/index.html
  *  External link http://bitsandchips.me/Shef_CodeFirst_Python/ failed: 404 No error
--
- _site/blog/fun-with-strace/index.html
  *  External link https://github.com/drj11/dot failed: 429 No error
  *  External link https://github.com/drj11/dot/commit/7d097ba875e2cca186b8d659d3510c2af5c8df1b failed: 429 No error
--
- _site/blog/icms-2017/index.html
  *  External link https://twitter.com/Renou_Martin failed: 404 No error
  *  External link https://www.sheffield.ac.uk/physics/contacts/mark-quinn failed: 404 No error
--
- _site/blog/modernfortran2017/index.html
  *  External link https://www.oerc.ox.ac.uk/introduction-modern-fortran-course-materials failed: 404 No error
--
- _site/blog/mozsprint-2017-at-the-university-of-sheffield/index.html
  *  External link https://foundation.mozilla.org/en/opportunity/global-sprint/ failed: 404 No error
  *  External link https://github.com/TyJK/EchoBurst/blob/master/Youtube%20Caption%20Dump/Instructions.md failed: 429 No error
  *  External link https://twitter.com/cypath failed: 404 No error
  *  External link https://www.linkedin.com/pulse/aletheia-mozilla-global-sprint-2017-kade-morton?trk=v-feed&lipi=urn%3Ali%3Apage%3Ad_flagship3_detail_base%3BVDNGKz72yDQY9IDHaKn6gg%3D%3D failed: 404 No error
--
- _site/blog/sge-job-validation/index.html
  *  External link http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/sge.html#running-batch-jobs-on-iceberg failed: 404 No error
--
- _site/blog/sheffieldr-hacktoberfest/index.html
  *  External link https://t.co/BE0Bt5Kszc failed: 429 No error
  *  External link https://t.co/zNjMVUkRjP failed: 429 No error
  *  External link https://twitter.com/soayipm failed: 404 No error
  *  External link https://twitter.com/soayipm?ref_src=twsrc%5Etfw failed: 404 No error
--
- _site/blog/soft-carp-at-tuos/index.html
  *  External link https://www.sheffield.ac.uk/library/libstaff/researchservices failed: 404 No error
--
- _site/blog/the-university-of-sheffield-named-an-nvidia-gpu-education-center/index.html
  *  External link https://www.sheffield.ac.uk/dcs/latest-news/nvidia-1.587214 failed: 404 No error
--
- _site/blog/tmux-intro/index.html
  *  External link http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/sge.html failed: 404 No error
  *  External link https://github.com/willfurnass/dotfiles/blob/master/tmux/.tmux.conf failed: 429 No error
--
- _site/blog/turing-way/index.html
  *  External link https://github.com/alan-turing-institute/the-turing-way/blob/master/chapters/open_research.md failed: 429 No error
  *  External link https://github.com/alan-turing-institute/the-turing-way/blob/master/chapters/reproducibility.md failed: 429 No error
  *  External link https://github.com/alan-turing-institute/the-turing-way/blob/master/chapters/version_control.md failed: 429 No error
  *  External link https://github.com/alan-turing-institute/the-turing-way/blob/master/humans.md failed: 429 No error
--
- _site/blog/willfurnass-intro/index.html
  *  External link http://www.acrc.com/deep-learning/ failed: 404 No error
--
- _site/community/resources-and-equipment/languages/r.html
  *  External link https://github.com/RSE-Sheffield/Code_cafe/tree/master/First_steps_with_R failed: 429 No error
- _site/community/seminars/index.html
  *  External link https://learningpatterns.me/conda-rses-pres/ failed: 404 No error
  *  External link https://sites.google.com/a/sheffield.ac.uk/rcg/my-blog/research-computing-notes/firststepsinscientificprogramming failed: 404 No error
--
- _site/contact/becky-arnold/index.html
  *  External link https://www.sheffield.ac.uk/physics/news/programming-skills-sessions failed: 404 No error
--
- _site/training/deeplearning/index.html
  *  External link https://developer.nvidia.com/deep-learning-resources failed: 404 No error
  *  External link https://sites.google.com/a/sheffield.ac.uk/rcg/my-blog/research-computing-notes/deeplearningusingmatlab2018bgpurequired failed: 404 No error
  *  External link https://sites.google.com/a/sheffield.ac.uk/rcg/my-blog/research-computing-notes/neuralnetworks-onlineresource failed: 404 No error
--
- _site/training/workshop/2016-08-02-reproducible-research-using-r-rstudio-git-and-github/index.html
  *  External link http://www.isbe2016.com/ failed: 401 No error
- _site/training/workshop/2016-10-11-code-caffe-introduction-to-mathematica/index.html
  *  External link https://github.com/RSE-Sheffield/Code_cafe/tree/master/WolframCodeCafe failed: 429 No error
- _site/training/workshop/2017-04-20-amazon-aws-immersion-day/index.html
  *  External link https://aws.amazon.com/events/immersion-sheffield/ failed: 404 No error

**Comment by willfurnass** [comment]
Plus https://rse.shef.ac.uk/community/resources-and-equipment/ includes a broken link to https://rse.shef.ac.uk/community/resources-and-equipment/languages/rstats; this should probably point at https://rse.shef.ac.uk/community/resources-and-equipment/languages/r.html.

**Comment by Robadob** [comment]
Summit probably wants to link to : https://docs.olcf.ornl.gov/ (This page says 'the system user guide' is the definitive guide to summit: https://www.olcf.ornl.gov/olcf-resources/compute-systems/summit/)

**Comment by Robadob** [comment]
https://twitter.com/Renou_Martin -> https://twitter.com/martinRenou (Appears to have changed his alias ~July 2019, but found a tweet that had his old alias link to medium, which links back to his current twitter alias.

**Comment by Robadob** [comment]
This one might be lost forever: https://www.sheffield.ac.uk/dcs/latest-news/nvidia-1.587214

Google lists https://www.sheffield.ac.uk/faculty/engineering/news/nvidia-1.587003 with a similar title, however that just redirects to engineering home. And searching nvidia doesn't pull any results on that page. I'd assume the uni website rewrite might have lost news from 2016.

**Comment by Robadob** [comment]
http://www.isbe2016.com/ Probably a website for a conference in 2016, now parked with some chinese language page.
Either of these might suffice, otherwise kill the link
http://www.exevent.co.uk/isbe2016
https://twitter.com/isbe_exeter?lang=en

**Comment by Robadob** [comment]
https://developer.nvidia.com/deep-learning-resources -> https://developer.nvidia.com/deep-learning

This is the most general deep learning page, links out to alot of other stuff.

**Comment by Robadob** [comment]
https://github.com/geraldgallagher/culbibbs
Has no public repos, probably made it public temporarily during hackathon.

**Comment by Robadob** [comment]
https://twitter.com/soayipm -> https://twitter.com/tamorajames
Embedded tweet has the correct alias.

**Comment by Robadob** [comment]
@willfurnass HTTP 429 is "Too Many Requests", quite a few of those are that code.

http://badge.fury.io/gh/flesler%2Fjquery.scrollTo (This link is fine, had 429 error)

These two links are both twitter short urls, might want to just replace them with the actual URL, again 429 error
https://t.co/BE0Bt5Kszc -> https://github.com/ropensci/rnbn/pull/19
https://t.co/zNjMVUkRjP -> https://github.com/search?utf8=%E2%9C%93&q=user%3Aropensci+user%3Aropenscilabs+label%3Ahacktoberfest+state%3Aopen+type%3Aissue&type=
