### ISSUE TITLE
CI job for internal link checking

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#239]
Our current jekyll + gh-pages setup doesn't give a fart about there being broken internal links - need to set something up for this.

@twinkarma In [script/cibuild](script/cibuild), called from [.travis.yml](.travis.yml), you commented out `bundle exec htmlproofer --allow-hash-href ./_site` back in Jan 2019 - can you remember why?  

---

EDIT: useful htmlproofer args for internal link checking (assuming htmlproofer invoked using `bundle exec htmlproofer $ARGS ./_site`): 

- `--disable-external` 
- `--allow-hash-href`
- `--empty-alt-ignore`
- `--internal-domains=rse.shef.ac.uk,rse.sheffield.ac.uk`
- `--assume_extension` - so htmlproofer will try GETting e.g. `programming.html` if `programming` can't be found.

**Comment by twinkarma** [comment]
There might have been a good reason for this at the time I honestly can't remember. Let's put it back in then if you're not finding any build issues with it enabled.

**Comment by ptheywood** [comment]
I'd guess it might generate false positives due to requsts being timed out due to spam / travis' IP ranges may be blocked from certain domains?

**Comment by willfurnass** [comment]
Tried re-enabling it in a PR for switching to GHA (#320)

**Comment by willfurnass** [comment]
I think the next key thing to figure out re this is:
 - if building the site generates e.g. `_site/training/programming.html` from `pages/training/programming/index.md`
 - but GH Pages is happy to serve that up as `/training/programming` (crazy logic, IMHO)
 - and our site contains internal links to `/training/programming`
 - then how should meaningfully check internal links?

Some possibilities:
 - Tell the link checking tool to ignore certain links? 
 - Tell the link checking tool to omit .html file extensions when trying to resolve internal links, so as to mimic the behaviour of the GH Pages web server?
 - Somehow tell Jekyll to use different rendering logic to e.g. render `pages/training/programming/index.md` as `_site/training/programming/index.html`?

The third of those approaches sounds most attractive to me.  Any comments @ptheywood or @twinkarma ?

**Comment by ptheywood** [comment]
Removing file extensions from URI's is a very, very common pattern with the web and generally is prefered. 

From the [`html-proofer` readme](https://github.com/gjtorikian/html-proofer#configuration) it looks like the `assume_extension` configuration property can be used to support waht we want? Not sure if the expected value should be `true` or `.html` though , nor how to pass that via the cli

**Edit** From the [`Using with Jekyll` section](https://github.com/gjtorikian/html-proofer#using-with-jekyll):
```
htmlproofer --assume-extension ./_site
```

**Comment by willfurnass** [comment]
@ptheywood Good spot!  Yes, that helps!
