### ISSUE TITLE
Replace eventbrite_id header info with Eventbrite links in page/post/event bodies 

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#244]
Error msg displayed in iframe placeholder in Firefox 75:

> Blocked by X-Frame-Options Policy
> 
> An error occurred during a connection to www.eventbrite.co.uk.
> 
> Firefox prevented this page from loading in this context because the page has an X-Frame-Options policy that disallows it.

Build PR #243 and view the `workshop-2020-05-14-remote-reprohack` page to see this in action.

Chromium also blocks Eventbrite iframes but doesn't render an error message.

@ptheywood Any comments on this?

**Comment by ptheywood** [comment]
Looks like eventbrite don't want people iframing their content, which is fair enough.

Iframes are probably best avoided to be honest, they tend to not match the rest of the site, the referenced content may change at any time and probably don't work particularly well on mobile devices either.

**Comment by willfurnass** [comment]
Okay, let's remove all `eventbrite_id`s from YAML headers, ensure Eventbrite links exist in page/post/event bodies and add a note to the README about this issue then.

**Comment by ptheywood** [comment]
Might be easier to just  modify the template to not make use of it? / as well as remove them. 

https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/c437b5926dc3a5b2163b94b3ce209650943c85ae/_layouts/event.html#L50-L57
