### ISSUE TITLE
Review RSE Community section

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#264]
- [ ] Drop seminar series in preparation for relaunch as LunchBytes.
- [ ] Remove dead links / defunct organisations (see WIP PR #240)
- [ ] Check resource and equipment list is up to date
- [ ] Do we need the Deep Learning events bits?

**Comment by willfurnass** [comment]
> Drop seminar series

Would be a shame to purge the overview info on historic seminars from our site; perhaps we should move the existing page under a new `LunchBytes (talks)` page.  Sound reasonable?

**Comment by bobturneruk** [comment]
Yes. I did not intend to get rid of the historic stuff. Are they still there under events as of #266?

**Comment by bobturneruk** [comment]
Website has changed substantially since this was raised. No longer relevant.
