### ISSUE TITLE
Add event for ALIFE FLAME GPU tutorial

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#277]

**Comment by Robadob** [comment]
This has been and gone, unless you want a retrospective.

**Comment by willfurnass** [comment]
@Robadob A stub event would still be useful for tracking events we've been involved in.

**Comment by Robadob** [comment]
@MILeach may be able to provide that if @mondus is too busy, he developed the content (it was transferred from FGPU1 to FGPU2 iirc).
