### ISSUE TITLE
Add newletter to RSS feed

### ISSUE THREAD

**Issue by coolmule0** [RSE-Sheffield/RSE-Sheffield.github.io#279]
Currently only the blogs are in the RSS feed. I think newsletters would be a good inclusion

**Comment by willfurnass** [comment]
@bobturneruk What do you think to the newsletters being a blog post?  (I really should have raised this question earlier)

**Comment by bobturneruk** [comment]
That's how I started doing them (tagged somehow) but after some chat on slack it was thought better that they were their own thing.

**Comment by willfurnass** [comment]
Related issue - should newsletters be blog posts (#280)?
