### ISSUE TITLE
Ensure newsletters have some visibility on home page?

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#280]
Currently maintained as a separate Jekyll collection for ease of management but more visible if tagged blogposts?  Could we still have a separate newsletter index if newsletters are tagged blog posts?  NB if we do make any structural changes we'll need to maintain the permalinks to the published newsletter(s).

**Comment by Robadob** [comment]
Might be easier to somehow shoehorn a link to the most recent newsletter into the home page?

**Comment by ptheywood** [comment]
Having a list of the N most recent newsletters in a similar fashion to how upcoming events are listed shouldn't be too difficult either, just the homepage will get more complex as more content gets added to it. Could easily go below the list of events, although it would get pushed down if we had many events coming up.  

Infact see #271 already as a duplicate issue that Bob had already created.
