### ISSUE TITLE
Add a link to join mailing list to homepage

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#297]
Next to follow on Twitter / GitHub

**Comment by willfurnass** [comment]
@drj11 commented yesterday that the mailing list is not easy to find on the RSES site.

**Comment by drj11** [comment]
Personally I'd expected to find it under the "Community" menu item. But mostly I google for it. Earlier (last year?) I specifically asked a friend to see if they could find and join the mailing list, and they were able to find it without any problem.

**Comment by bobturneruk** [comment]
This is now on the homepage.
