### ISSUE TITLE
Newer content from the current site

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#3]
Whilst this version is being developed changes are still being made to the current site (i.e. new seminars). When this site is ready to go we will need to make sure that newer content has been added.

**Comment by willfurnass** [comment]
Yes. @twinkarma: do you have a record of which commit in https://github.com/RSE-Sheffield/RSE-Sheffield.github.io you migrated content from?

**Comment by twinkarma** [comment]
No but it's relatively recent. It's after our last team meeting so would be around mid December

**Comment by twinkarma** [comment]
From what I can see, I was the last one to update the RSE website. The content of the new site should actually be up to date.

**Comment by willfurnass** [comment]
Looks like your post from 2018-12-20 is exclusive to the older site, so I think we'll need to migrate all changes to the old site made after that (after commit 24396f33e394f6cca9f3645a500f9d857d0bbdd2).

**Comment by twinkarma** [comment]
That one is for the Jan DL event. On the new site I've only added it as an 'event' instead and didn't add a blog post promoting the event as the home page now lists both blogs and events. I think this should be how it's done from now on to reduce on redundancy.

**Comment by ptheywood** [comment]
Content Identified as needing to be included:

+ [x] Bio for David Jones
    + fb43fc2af54540c2ac8473b232df446e76797d13
+ [x] Bio for Becky Arnold
    + eb4d2f0eacdefadf4a8fc961815551b0bf8dc3ed
    + f6ba2a3a4b496c05d7c193914a95677dd70bd856
    + 122c3c8536237a963de7274b4e6977ce788f3633
+ [x] Repost of Becky's SSI blog post
    + ab3b2346b77b6aa062260963429cf80011ae8747
    + 2c43fce029cb8caf96a6d47a3f56588b369affa4

**Comment by ptheywood** [comment]
Fixed by ca7e805673725d21aec3de3be7695d03fa0780a7
