### ISSUE TITLE
Standardise on Ruby gem versions, especially Jekyll

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#315]
@davidwilby and I discovered today that he's been locally testing with 4.0.0, I've been testing with 3.8.5 but GH Pages uses 3.9.0 at the time of writing: https://pages.github.com/versions/

How should we encourage standardise on a test+production Ruby env?  Encourage contributors to run `bundle update` periodically to refresh the local Ruby environment?

**Comment by ptheywood** [comment]
given the github-pages gem is mentioned in the Gemfile always running bundle update should catch that, although I'm unsure on whether that woudl downgrade a pre-installed version of jekyll or not, so encouraging running update seems sound.

Regularly updating the github pages gem is also githubs reccomendation: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll#updating-the-github-pages-gem

**Comment by willfurnass** [comment]
Ha, just noticed that we have a note about `bundle update` in the README that @ptheywood and I added in April.

Happy that we can close this?
