### ISSUE TITLE
Add a "hero element" to homepage for code clinics

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#334]
Make it easy to get to these with a big fat button thing?

https://en.wikipedia.org/wiki/Hero_image

**Comment by willfurnass** [comment]
A pic of a CC helper and researcher working together or something similar?

**Comment by bobturneruk** [comment]
https://www.pexels.com/search/coding%20help/
https://unsplash.com/s/photos/coding-help

I'm not good on the aesthetics, but am in favour of a big colourful button.

**Comment by willfurnass** [comment]
@bobturneruk I've just remembered that a while back when @mozhgan-kch was part of the team she designed great a Code Clinic logo for a flyer we never got printed - we could add that logo to the CC page.

https://drive.google.com/file/d/12a3LfbkvDekgJMaJ7MHzGeZzBgmt5l00/view?usp=sharing

**Comment by bobturneruk** [comment]
I think that would be a perfect big button on the homepage. Maybe with a
few descriptive words embedded in the image....

**Comment by willfurnass** [comment]
Full flyer with more words here:

https://drive.google.com/file/d/10sFcomwFR6c8n4-TGt_j7BlQ1-U4EALI/view?usp=sharing

**Comment by bobturneruk** [comment]
Resolved by #343
