### ISSUE TITLE
Visually distinguish future and past events.

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#35]

**Comment by twinkarma** [comment]
@willfurnass Any ideas on what'd be good? Just make the previous events links grey?

**Comment by willfurnass** [comment]
On https://rse.shef.ac.uk/events/ what would be nice are:
 - separate lists for future and past events i.e. headings;
 - either hide past events list or make a separate column;
 - (as you suggested) grey font for past event titles

Also, future events should be in chronological order

**Comment by ptheywood** [comment]
What should the behaviour be when JS is not enabled - Ie. a static version of the page. 

Currently the listings are in reverse chrono by default so upcoming events are nearer the top in the case of no javascript / No recent builds.

One option is to output future events in chrono follwed by older events in reverse chrono, then only use JS to move the now-past events from the future list to the past list? That shouldn't be too much to implement.

**Comment by willfurnass** [comment]
`<marquee>PLEASE ENABLE JAVASCRIPTS</marquee>`

**Comment by willfurnass** [comment]
Your suggestion sounds sensible, but I don't think we should make much effort to cater for those with JS disabled.
