### ISSUE TITLE
Add basic CoC for training and other events

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#354]
I've started adapting http://www.archer.ac.uk/training/code-of-conduct/ so we can use a version for our events/training.

**Comment by willfurnass** [comment]
@bobturneruk pointed out that all GitHub users are covered by:

 https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-community-guidelines

Could possibly reference this in our CoC or just at events where it's relevant.

**Comment by willfurnass** [comment]
@mondus notes that the RSE Society has a good CoC that we may want to use instead / borrow from: 

https://society-rse.org/about/code-of-conduct/

**Comment by bobturneruk** [comment]
Very much in favour of not reinventing.
