### ISSUE TITLE
Remove redundant timestamps from post lists on homepage?

### ISSUE THREAD

**Issue by Robadob** [RSE-Sheffield/RSE-Sheffield.github.io#361]
Including time in the timestamp feels a bit redundant, given they all say `12:00`.

![image](https://user-images.githubusercontent.com/742154/104195299-552fa200-541a-11eb-895a-f71bb42469db.png)

These two lines would need updating:
https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/34781d60a247e6d825297c324bc807446faa2527/_includes/newsletters_list_item.html#L18
https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/34781d60a247e6d825297c324bc807446faa2527/_includes/post_list_item.html#L18

**Comment by willfurnass** [comment]
A good idea.
