### ISSUE TITLE
GPSS PDF embed not being served over https

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#457]
The `Multiple output Gaussian processes for GPy` project description includes an embedded pdf, which is blocked from loading by (most? all?) browsers as it is being loaded from a `http` source, compared to `https` for our site. 

The content does not appear to be available over https, so the embed should  be removed or the content should be hosted somewhere that is available via https.

``` html
<embed src="http://gpss.cc/gpss17/slides/multipleOutputGPs.pdf#page=4" type="application/pdf" />

```

[source](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/master/_project_descriptions/gpy.md#L7) (although you can't actually view markdown files unrendered on the website)

**Comment by Robadob** [comment]
> content should be hosted somewhere that is available via https.

Is this something that's appropriate to make a copy of in our site assets @bobturneruk ? (Appears to be your project)

**Comment by ptheywood** [comment]
This content now appears to be available over https, so we just need to ammend the embed to be https.

https://gpss.cc/gpss17/slides/multipleOutputGPs.pdf#page=4
