### ISSUE TITLE
Project filter doesn't work as expected

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#459]
![image](https://user-images.githubusercontent.com/34244196/117456824-89d2e680-af40-11eb-899d-6f928d6a7afc.png)
I select "active" but still see "completed".

**Comment by Robadob** [comment]
Which web browser is this?

I believe it works for myself @ptheywood and @willfurnass

**Comment by Robadob** [comment]
This is how it looks for me on Chrome.
![image](https://user-images.githubusercontent.com/742154/117457421-1aa9c200-af41-11eb-88c6-b843b5c09d9d.png)

**Comment by bobturneruk** [comment]
Google Chrome

Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by bobturneruk** [comment]
Windows 10

**Comment by Robadob** [comment]
Try shift + refresh?

**Comment by bobturneruk** [comment]
Yes - that worked, thanks! Cache issues I guess.

**Comment by bobturneruk** [comment]
I'll try on IE3 next.

**Comment by Robadob** [comment]
I don't think it's using anything fancy. Pete did suggest we use data attributes, which definitely wouldn't work in internet explorer, but they wouldn't make multiple tags work nice.
