### ISSUE TITLE
Capture analytics data in a way we're all happy with

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#479]
We're not tracking 'conversions' to project enquiries but there is value in tracking the impact of the newsletter, LunchBytes, blog posts etc as that kind of data should
 - should be of interest to those that support/underwrite the team (can be presented via RSE steering group meetings)
 - could be used as evidence in SRDS/ACP processes
 - could be used when making submissions as part of outward-facing impact statements e.g. Hidden REF.

We previously started looking at Google Analytics (PR #332) but that stalled.  A more privacy-oriented alternative might be better.

Things found by @bobturneruk
 - https://plausible.io/
     - cookie-free option at [£6 a month](https://plausible.io/#pricing)
     - AGPL-licensed code here: https://github.com/plausible/analytics/

**Comment by willfurnass** [comment]
Response from TUOS GA admins re using central GA account:

> Thank you for your email and sorry for the delay in getting back to you. I've checked and as this is a subdomain, the site is not part of the central Google Analytics setup. This happens by default for CMS sites but not for other sites. So you'll need to set up and run your own Google Analytics account for this specific subdomain which will involve registering for analytics and installing the tracking code on the site. The developer of your website should be able to help with this, or if not there are plenty of articles out there giving instructions, for example: https://support.google.com/analytics/answer/1008015?hl=en

**Comment by bobturneruk** [comment]
Thanks @willfurnass - I guess we need to figure out if Google's code provides GPDR / cookie rules compliant request for consent.

**Comment by bobturneruk** [comment]
Closed by #487
