### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#540]
https://rse.shef.ac.uk/blog/all

**Comment by Robadob** [comment]
Hmm, it did work when I initial setup the pagination.

**Comment by Robadob** [comment]
Ah, it was intentionally removed by me. But it appears I removed it from posts and not the directory

https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/commit/137a543ff64257d516467ada46d35bd336eba93f

**Comment by Robadob** [comment]
Looks like this just needs nuking too (unless the all page wants to be revived?).

https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/e2a445173ac253217bfab627daa18717a5a9eac5/blog/index.html#L54
