### ISSUE TITLE
Cleaner Homepage

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#556]
Following some discussion on #555 via slack, the homepage has become cluttered / a little messy overtime and would benefit from some changes to clean it up and improve the ability to emphasise key content.

This could include, but not be limited to:

+ Reduce the use of fonts stlyes and sizes on the hompage
+ Reduce the number of elements competing for focus at the top of the page (i.e. move the video)
+ Reduce the size of the text describing RSEs in general and the group, either in font size/weight or the length of prose in the large font. 
+ Reduce duplication of content (logo) on the hompepage
+ Reduce social media clutter, it is not as important as the calls to action links
+ Move the presentation recording to another page, 
+ Reduce the number of blog entries and past events shown on the homepage, to promote the contact us section (content could also be improved)

My comments from slack below so they do not dissapear

> If you want someone to find something it needs to stand out, but if everything is intended to stand out then nothing does.
Reducing the number of text sizes, fonts and large block elements like the video so that the buttons actually stand out would be one way to achieve this.
If it were entirely up to me I'd remove the video from the home page and move it to one of the about pages, removing one of the large elements on the home page that although nice people who find our website probably aren't going to sit through a 20 minute video.
The social buttons (twitter, twitter and github) below the large button links could be cleaned up / moved too potentially. Two twitter buttons are pointless.
Github's not social media and most people won't benefit from following the org, just  linking to it would be more than sufficient.
The very long text next to the logo in the serif font is also excessively large really / distracting, it either needs to be shorter or smaller.
The logo (including the video preview) is on the home page 3 times. It's a nice logo but it doesn't really need that much of the home page dedicated to it.
Reducing the number of blogs posts and previous events listed on the homepage would lean it up too, but most of that is below the fold at the moment anyway so its' less important anyway, other than pushing the contact us section further down. (Most people are happy scrolling now anyway so what is above/below the fold doesn't matter too much, but it's ingrained in me from my time as a webdev back when people had smaller monitors and worse internet connections and even SEO took it into account)

**Comment by twinkarma** [comment]
@EdwinB12 to do on hack day?

**Comment by tdjames1** [comment]
See also #763

**Comment by tdjames1** [comment]
Most of the points raised in this issue have now been addressed, so closing this ticket.
