### ISSUE TITLE
Publishing Research Software Reference Page

### ISSUE THREAD

**Issue by Robadob** [RSE-Sheffield/RSE-Sheffield.github.io#588]
This could be a useful living page that we direct people to, and expand as we find new use-cases which don't fit.

*Notes from CC Helpers GChat*

0. Make sure you are legally allowed to do so (check with your PI or funder), or are otherwise relaxed about this.
0. [Licence your code?](https://choosealicense.com/)
1. Make your environment reproducible (this varies based on what language/tools your software uses)...
    * Python: [pip requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files), setuptools/`pyproject.toml`/`setup.cfg`, [Conda environment.yml](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment)
    * R: [.renv](https://rstudio.github.io/renv/articles/renv.html) *(The linked page seems too general at a glance)*, [anna's guide](https://annakrystalli.me/rrresearchACCE20/managing-dependencies.html)
    * C++/C/Fortran: [Spack?](https://spack.readthedocs.io/en/latest/environments.html), CMake?
    * docker/apptainer
    * matlab: document your required toolboxes (and hope for the best)
2. Write a readme (and test it on a clean machine/hpc)
3. Create a Git release with [Orda](https://orda.shef.ac.uk/) ([Zenodo](https://zenodo.org/) also works, however Orda is preferred by UoS) so you have a doi
4. Cite your software using the `doi`, report it to ResearchFish under `Software & Technical Products > Software` or similar.

**Comment by davidwyld** [comment]
Some other resources on this topic:
* https://www.bristol.ac.uk/acrc/research-software-engineering/software-howtos/how-to-publish-software/
* https://www.reading.ac.uk/research-services/-/media/project/functions/research-and-enterprise-services/documents/softwareguide.pdf?la=en&hash=1E2D2581EF0FDEE9C768F2C7B0472CFA
* https://libguides.mit.edu/software

**Comment by ns-rse** [comment]
I happened across an article on this topic a day or so ago...

* [Beyond advertising: New infrastructures for publishing integrated research objects](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009651)

**Comment by twinkarma** [comment]
To be covered in the FIAR 4 Software content
