### ISSUE TITLE
Improve Training Page

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#589]
- [x] Highlight training courses that are currently scheduled or are likely to be scheduled.
- [x] Make courses sound more appealing.
- [x] Review organisation of content.

**Comment by mondus** [comment]
I would suggest to separate out regular delivered training and custom delivered training. We should also have a clear vision on what training we deliver. I.e. Why do we deliver training and on what general subjects as well as how this links with other training available.

**Comment by bobturneruk** [comment]
Thanks @mondus!
