### ISSUE TITLE
Show latest blog post when view blog page

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#6]
Would be nice to be able to see latest blog post and list of older posts - can they be viewed simultaneously?

**Comment by twinkarma** [comment]
@willfurnass  Do you mean we show the content of the latest blog post? How many of the latest ones? Do we do this for the home page as well as the /blog/ page?

**Comment by willfurnass** [comment]
My personal preference would be to show paginated blog posts (one post per page) under `/blog` but keen to learn what others think; can discuss at the team meeting this week.

**Comment by ptheywood** [comment]
There definately needs to be some form of pagination, but it would still be good to have a list of posts along with either showing the latest post(s) on the blog page.

**Comment by ptheywood** [comment]
https://jekyllrb.com/docs/pagination/

**Comment by Robadob** [comment]
Made a start on this, visible on my development mirror [here](https://rse-mirror.robadob.org/blog2/).

Few things left to do.

- [x] Relocate existing `root/blog` to `root/blog/all` or similar.
  - [x] Link blog post index from blog page footer
  - [x] Relocate blog pagination to `root/blog`
    - [x] Rename dir
    - [x] Update path on config/yml
    - [x] Relocate the `pages/blog-all.md` file to better represent it's new permalink?
- [x] Add proper styling for the pagination links.
  - [ ] Do we want prev/next or 1/2/3/4/.../n?
  - [x] Need css magic to center the dynamically sized div
  - [x] Style/Reword the link to all posts
  - [ ] 'Previous' is longer than 'Next', which makes link to all look off center. Either swap Prev/Next for unicode arrows, or make the central label ( Page: x of y ) the link
- [x] Add some kind of `<hr/>` to separate posts
  - [x] How to not add this separator after the final post on a page?
- [ ] Style blog title to differentiate it from blog post title's (both `h1`), this probably requires some template tweaking.
  - [x] Perhaps it should be changed to RSE Sheffield Blog at the same time?
- [ ] There are also Previous/Next links at the bottom of individual blog post pages which could do with improved styling at the same time?
