### ISSUE TITLE
Ammed old job advert blog posts once they're no-longer active

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#607]
Searching for RSE Sheffield vacancy currently (for my potentially biased google search) finds the [May 12th blog post](https://rse.shef.ac.uk/blog/2022-05-12-rrse/) for the job vacnancy, rather than the currently open vacancy. 

This page does not mention any application deadlines, simply linking to the job advert which has dissapeared as it is no longer active. 

We should probably ammend pages like this after the applications have closed so it is clear that it is no longer available.

**Comment by bobturneruk** [comment]
The first link on this has been updated to the new Ad. Missed the second one.
