### ISSUE TITLE
Training course listings [bug]

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#630]
https://rse.shef.ac.uk/pages/training/courses/git_Hero.html should only list future instances of this course, but lists all future events:
![image](https://user-images.githubusercontent.com/34244196/194315792-ae152d96-106f-4d6b-8bdc-f1e2ebc56ddb.png)

**Comment by Robadob** [comment]
https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/master/pages/training/courses/git_Hero.md
Try changing `{% include events_list_upcoming.html %}` to `{% include events_list_upcoming.html category=gitzerohero %}`

At a glance [that include](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/master/_includes/events_list_upcoming.html) has a `category` parameter which is supposed to perform filtering. No idea if you need to quote `gitzerohero` or similar.

**Edit:** Didn't work. Retrying with quotes.

**Edit2:** Quotes worked, PR soon.
