### ISSUE TITLE
Hide body of Benchmarking FLAME GPU 2

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/RSE-Sheffield.github.io#705]
Currently the recent post [Benchmarking FLAME GPU 2 on H100, A100 and V100 GPUs](https://rse.shef.ac.uk/blog/2023-08-18-benchmarking-flamegpu2-on-h100-a100-and-v100-gpus/) is all displayed on the front page...

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/17566406/a65194b6-a52a-4b57-bbf8-b032b8267d46)

Adding the `excerpt_sepratator` (`<!--more-->`) will hide the body from the blog page.

**Comment by ptheywood** [comment]
Ta, I'd only viewed the post itself and not the blog page.
