### ISSUE TITLE
Add Mastodon verification link to index

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/RSE-Sheffield.github.io#708]
Add <a rel="me" href="https://fosstodon.org/@RSE_Sheffield">Mastodon</a> to index.html of [rse.shef.ac.uk](https://rse.shef.ac.uk/) so that the site link in the account profile appears as Validated.

**Comment by Robadob** [comment]
Offtopic, opened the mastodon page and some text is falling out of the header.

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/742154/cc134f6a-c27f-47cc-93b1-57510430987e)

**Comment by ns-rse** [comment]
Hmm, tricky I think it perhaps depends on screen resolution and zoom level.

Looks ok for me here, screenshot...

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/17566406/f77e3599-bb11-44e1-9327-88610981e7e8)

...and the original image...

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/17566406/79e4104c-a7ec-4112-9fa4-145bc8d56e7f)

I'll crop a bit off the top anyway, thanks @Robadob :+1:

**Comment by Robadob** [comment]
Yeah I typically run web browsers on half screen, commonly breaks sites.

**Comment by ns-rse** [comment]
I've cropped some of the top off anyway so should be a little better.
