### ISSUE TITLE
Summary of funded Proposal calls

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/RSE-Sheffield.github.io#816]
We have funded three positions at 0.5 FTE for six months.

A short blog post can be made with an abstract summarising each of the funded proposals. We can use the material from the submissions

+ [Tools to analyse splice-aware SLAMseq](https://drive.google.com/file/d/1TO4HkJS9ar-KXBtANioxfgST_we5f231/view?usp=drive_link) - @ns-rse
+ [HYBIRD: a Particle-Fluid Engineering Simulation Tool (HYPFEST)](https://drive.google.com/file/d/16jcMXeA8a9GYS1IxceXfz28-Jc1Qsy_C/view?usp=drive_link) - @Robadob 
+ [PolyChron: A tool for archaeologists for the management of absolute and relative dating evidence](https://drive.google.com/file/d/11n_jW-NHmIG2EXnicIvYv9wODsi0_5Zh/view?usp=drive_link) - TBC

**Comment by Robadob** [comment]
By tagging me, I assume I'm to write the one for the project I'm working on?

**Comment by ns-rse** [comment]
Nope, not at all, assigned to myself and I'll summarise it.

**Comment by Robadob** [comment]
Ok fair enough, with approval, will perhaps be good to do a follow-up at the end of each project to summarise the success.

**Comment by ns-rse** [comment]
Yep, I mentioned that to @Romain-Thomas-Shef the other day and was thinking asking the PIs of each project for their perspective on how the projects went.
