### ISSUE TITLE
Section titles are hidden behind the top bar when directly linked

### ISSUE THREAD

**Issue by martinjohndyer** [RSE-Sheffield/RSE-Sheffield.github.io#841]
Whenever you use a URL containing a section tag (e.g. the table of contents on https://rse.shef.ac.uk/training/programming) the actual section header and the first few lines of text are hidden behind the top bar. 

As a real example, in one of the FAIR2 pages I want to write

> There is [a separate module](https://rse.shef.ac.uk/training/fair4rs/#testing-and-continuous-integration) which will go into more detail on testing next semester.

If you click on that link the first heading you see is **Documentation**, and you have to scroll up to see the actual **Testing and Continuous Integration** section. I find this very disorientating.

This is probably an artifact of the particular template we're using, hopefully it's easy to fix in some CSS file.

**Comment by Robadob** [comment]
Something like this may work.

https://stackoverflow.com/a/24298427/1646387

**Comment by Robadob** [comment]
This works, tested in chrome dev tools.
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top
```css
html {
scroll-padding-top: 80px; /* A little higher could also work.*/
}

**Comment by Robadob** [comment]
(Note, this solution isn't responsive. But it's "good enough", my quick testing shows responsive only gets the bar smaller, though Pete claims it can get double height.)
