### ISSUE TITLE
Update statement on free at point of use training

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/RSE-Sheffield.github.io#852]
Currently reads...

> Bookings can usually be cancelled using eventbrite.com or, failing that, by emailing rse@sheffield.ac.uk.

But we don't currently use Eventbrite for organising training having moved to myDevelopment.

**Comment by Robadob** [comment]
MyDevelopment booking emails typically include

> Please note that a google calendar invitation has been automatically added to your diary.  If you can no longer attend the session, please ensure you withdraw your place via myDevelopment, rather than simply declining the google calendar invitation.

Feels like that's automated, possibly best to keep consistent language.
