### ISSUE TITLE
Blog post URLs with a trailing slash 404

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/RSE-Sheffield.github.io#86]
In the previous version of the website blog post URLs ended with a trailing slash, i.e. 

https://rse.shef.ac.uk/blog/whpc-isc-2019-call/

However, currently this results in a 404 and these urls may be linked from elsewhere (i.e. google).

The same URL without the trailing `/` does work I.e. 

https://rse.shef.ac.uk/blog/whpc-isc-2019-call

Ideally we need to find a way to make jekyll support both, in the same way that pages support both.

**Comment by willfurnass** [comment]
Oh FFS
