### ISSUE TITLE
Add documentation on event categories and how they work

### ISSUE THREAD

**Issue by ptooley** [RSE-Sheffield/RSE-Sheffield.github.io#94]
Readme needs details of what categories exist and how to add new ones.

**Comment by ptheywood** [comment]
https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/blob/master/README.md#adding-a-new-event-category

The readme already includes (vague) details of where the list of categories exists, and how to add new ones. 

It could be improved (as a part of a more useful readme on the whole)
